select DISTINCT DEVELOPERS.ID, DEVELOPERS.EMAIL, DEVELOPERS.FIRST_NAME, DEVELOPERS.LAST_NAME
from SKILLCODES join DEVELOPERS on ((DEVELOPERS.SKILL_CODE & SKILLCODES.CODE) != 0)
where SKILLCODES.CATEGORY = 'Front End'
order by DEVELOPERS.ID asc;